[package]
name = "nitrohydra"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.30"
egui_extras = { version = "0.30", features = ["all_loaders"] }
image = { version = "0.25", features = ["jpeg", "png"] }
md-5 = "0.10.6"
rayon = "1.11.0"
